name: Reportar Bug
description: Reportar um erro de comportamento ou bug do código
title: "[Bug]: "
labels: ["bug"]
body:
    - type: textarea
      id: o-que-houve
      attributes:
          label: O que houve?
          description: Descreva detalhadamente qual foi o problema encontrado
          placeholder: Ex Quando eu faço X, Y acontece
      validations:
          required: true
    - type: textarea
      id: como-reproduzir
      attributes:
          label: Como reproduzir o erro/bug
          description: Descreva detalhadamente o passo a passo para o erro acontecer
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Logs ou mensagens de erro
          description: Cole aqui o erro exibido no terminal ou traceback
      validations:
          required: true
    - type: input
      id: sistema
      attributes:
          label: Sistema operacional
          description: Informe qual sistema está usando
    validations:
      validations:
          required: true
    - type: dropdown
      id: versao-python
      attributes:
        label: Em qual versão do Python o erro acontece?
        description: Você pode selecionar mais de um ou nenhum se a informação não for relevante
        multiple: true
        options:
        - 2.7
        - >= 3.0 < 3.5
        - >= 3.6 < 3.9
        - >= 3.10
    - type: textarea
      id: notas
      attributes:
          label: Informações Adicionais
          description: Insira qualquer outra informação relevante relacionada ao erro/bug
      validations:
          required: false
